// Create the level 
// Add every space is 20px another 30px is added to the left and right
// Optimal size is 45 wide and 22 tall, the last five is for the resart block at the bottom
// x = walls / o = enemies
        

var Atlantis = [
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '           xxx      xxxxx      xxx           ',
    '                                             ',
    '                                             ',
    '                                             ',
    '    xxxxx  xxxx   xxxxxxxxx   xxxx  xxxxx    ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'ooooooooooooooooooooooooooooooooooooooooooooo',    
];

var Aether = [
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                   xxxxxxx                   ',
    '    xxxxxxxxxx                 xxxxxxxxxx    ',
    '                                             ',
    '                                             ',
    '           xxx      xxxxx      xxx           ',
    '                                             ',
    '                xx         xx                ',
    '                                             ',
    '    xxxxx  xxxx               xxxx  xxxxx    ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'ooooooooooooooooooooooooooooooooooooooooooooo',    
];

var Flatlands = [
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                   xxxxxxx                   ',
    '    xxxxxxxxxx                 xxxxxxxxxx    ',
    '                                             ',
    '                                             ',
    '           xxx      xxxxx      xxx           ',
    '                                             ',
    '     xxxxxx     xx         xx     xxxxxx     ',
    '                                             ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'ooooooooooooooooooooooooooooooooooooooooooooo',    
];