// Create the level 
// Add every space is 20px another 30px is added to the left and right
// Optimal size is 45 wide and 22 tall, the last five is for the resart block at the bottom
// x = walls / o = enemies
        
// Level identifier '1'
var Atlantis = [
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '           xxx      xxxxx      xxx           ',
    '                                             ',
    '                                             ',
    '                                             ',
    '    fffff  ffff   fffffffff   ffff  fffff    ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'ooooooooooooooooooooooooooooooooooooooooooooo',    
];

// Level identifier '2'
var Aether = [
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                   xxxxxxx                   ',
    '    xxxxxxxxxx                 xxxxxxxxxx    ',
    '                                             ',
    '                                             ',
    '           xxx      xxxxx      xxx           ',
    '                                             ',
    '                xx         xx                ',
    '                                             ',
    '    fffff  ffff               ffff  fffff    ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'ooooooooooooooooooooooooooooooooooooooooooooo',    
];

// Level identifier '3'
var Flatlands = [
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                   xxxxxxx                   ',
    '    xxxxxxxxxx                 xxxxxxxxxx    ',
    '                                             ',
    '                                             ',
    '           xxx      xxxxx      xxx           ',
    '                                             ',
    '     xxxxxx     xx         xx     xxxxxx     ',
    '                                             ',
    'fffffffffffffffffffffffffffffffffffffffffffff',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'ooooooooooooooooooooooooooooooooooooooooooooo',    
];